### ISSUE TITLE
Please Release Version: XXX

### ISSUE THREAD

**Issue by hwtcl** [webjars/lodash#21]
<dependency>
			<groupId>org.webjars.bower</groupId>
			<artifactId>dgrid</artifactId>
			<version>1.2.1</version>
		</dependency>
		<dependency>
			<groupId>org.webjars.bower</groupId>
			<artifactId>dstore</artifactId>
			<version>1.1.1</version>
		</dependency>
<dependency>
			<groupId>org.webjars.bower</groupId>
			<artifactId>xstyle</artifactId>
			<version>0.3.2</version>
		</dependency>
<dependency>
			<groupId>org.webjars</groupId>
			<artifactId>mathjs</artifactId>
			<version>3.11.5</version>
		</dependency>
		<dependency>
			<groupId>org.webjars</groupId>
			<artifactId>d3</artifactId>
			<version>3.5.5</version>
		</dependency>
		<dependency>
			<groupId>org.webjars</groupId>
			<artifactId>lodash</artifactId>
			<version>3.10.0</version>
		</dependency>

**Comment by jamesward** [comment]
You can release Bower WebJars on your own via http://webjars.org

For Classic WebJars, can you file version bump requests on the WebJar's GitHub repo.  I'll do the lodash down bump here in a minute.
